baseURL = 'http://longestboi.github.io'
languageCode = 'en-us'
title = 'Personal website'
theme = ['hugo-video', 'customTheme']
summaryLength = "2"

enableInlineShortcodes = true

[params]
debug = false

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  authors = 'authors'
  role = "roles"

[markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true
